### ISSUE TITLE
How to Iterate over Json array

### ISSUE THREAD

**Issue by CsBigDataHub** [manatlan/reqman#11]
How do I iterate over json array variable and run `GET`

example 

```
    - json.result.content: <<myValue>>  # ensure that the content is equal to myValue param
    - json.result.content.size: 2  
```  

here you have `content` array with size 2.

now I want run `GET` with, say `content.0.name` and `content.1.name` but programatically.

**Comment by CsBigDataHub** [comment]
@manatlan 
Probably can I do

```
- GET: /test/<<value>>
  foreach:
    - value: <<myValue.name>>
```
will it iterate through `json.result.content.0.name` and `json.result.content.1.name`

**Comment by CsBigDataHub** [comment]
```
- GET: /api/pets/v1/list
  tests:
    - status: 200
  save:
    pets: <<json.items>>

- GET: /api/pets/v1/info/<<id>>
  params:
    id: <<json.items.0.id>>
```

this is the example from documentation.

How can we pass all the `id` from `items` array to the `GET` call in a `foreach` loop

**Comment by manatlan** [comment]
Sure, there is a way to do that ...
I will write an unit test (because the unitest is gone ?!), to ensure it still works ... and will answer you tomorrow.

**Comment by manatlan** [comment]
In reqman3 : it doesn't work well ... there is a bug ... (the pets'list grows at each iteration) : It will be fixed in a future 3.0.3 release

BTW, it could work in reqman2 ...

the trick : is the py-method "iterate", which will convert your list in a "list of dict" ...
(each item of the list will expose a "i" var)

`
- GET: /api/pets/v1/list
  tests:
    - status: 200
  save:
    pets: <<json.items>>

- GET: /api/pets/v1/info/<<i.id>>
  foreach: <<pets|iterate>>
  params:
    iterate: return [ dict(i=i) for i in x ]
`

I've made a unittest, but the bug in reqman3 will be too complex to resolve, in this week ;-)
But you can consider it will work as is in a future version >3.0.2

**Comment by manatlan** [comment]
In fact, fixing this was really easy ...
the new 3.0.3 will fix that, and brings unitests on that
plan to release it at the end of the day ...

**Comment by CsBigDataHub** [comment]
> In fact, fixing this was really easy ...
> the new 3.0.3 will fix that, and brings unitests on that
> plan to release it at the end of the day ...

Awesome

**Comment by CsBigDataHub** [comment]
Also how do you handle nested arrays?

Say

`json.items.[].id.owners.[].name`

If there is GET by name and name is inside an array of owners which is inside array of items.

Can you please provide an example.

**Comment by manatlan** [comment]
The 3.0.3 is better, but not good (it doubbles the list during iteration) ...
(in fact, the fix will be complex ... expect it for the 3.0.4 :-( sorry )

> Also how do you handle nested arrays?

in that case, try to foreach in a foreach ... (no other way)

> Also this is just a thought, Is it going to be a huge effort to integrate json parsers?

no plan to integrate this ...
reqman use its own jpath-like ... which does the job ...
(perhaps, I could add another "jsonpath", as a 2nd/alternative syntax, when something will take the lead (commonly used in json world))

**Comment by CsBigDataHub** [comment]
> in that case, try to foreach in a foreach ... (no other way)

Can you please provide an example for this please.
I thought `You can use only one foreach per statement`.

**Comment by manatlan** [comment]
You must play with procedures, to be able to chain foreachs

Something like that (I'm on my phone)

- myproc:
  - GET: .....
    Foreach: ....

- call: myproc
  Foreach: ....

Like that, you can have nested foreach

Le ven. 9 juil. 2021 à 16:28, CsBigDataHub ***@***.***> a
écrit :

**Comment by manatlan** [comment]
3.0.4 is here, and everything works fine now ;-)

**Comment by CsBigDataHub** [comment]
@manatlan Thanks for your work.

**Comment by CsBigDataHub** [comment]
Hey @manatlan ,

Foreach is working great. I am not able to figure out nested foreach with procedures. can you help?
some test cases are here - https://github.com/CsBigDataHub/FHIR-TEST-IN_REQMAN

I was using http://hapi.fhir.org/baseR4/Patient?given:exact=Winney,Rodrigo&_pretty=true to test nested arrays in json.

**Comment by manatlan** [comment]
here is a working example ;-)

```
- GET: https://tmanatlan.appspot.com/fhir/all
  doc: get the list
  tests:
    - status: 200
  save:
    mylist: <<json>>

- fetch:
  - GET: https://tmanatlan.appspot.com/fhir/<<id>>
    doc: First Iteration over parent <<id>>/<<myparent>>
    tests:
      - status: 200
    save:
      mychildren: <<json.children|refacto>>
      myparent: <<json.name>>

  - GET: https://tmanatlan.appspot.com/fhir/<<idc>>
    doc: Second Iteration over child <<idc>>/<<mychild>> of the parent <<id>>/<<myparent>>
    foreach: <<mychildren>>
    save:
      mychild: <<json.name>>
    tests:
      - status: 200
  

- call: fetch
  foreach: <<mylist>>
  params:
    refacto: |
      return [dict(idc=i["id"]) for i in x]
```

sure, everything is possible ... but it can be very complex (to write/maintain)...
