### ISSUE TITLE
Support for environment variables Values

### ISSUE THREAD

**Issue by jrottenberg** [manatlan/reqman#3]
Hello !

Great tool,  heard of it through linuxfr. It seems to do exactly what I need but I'd like to use it in a very dynamic environment, ie each run will use a rml file, but I need to pass some variables (BUILD_ID, etc something I can not set in advance) to reqman.

I couldn't find a way to set a value with an environment variables but that would be awesome and close that issue ;-)

Thank you again for a great tool !

**Comment by manatlan** [comment]
the latest version do so (2.2.4.0) ;-)

```
$ reqman your.rml key:value
```

**Comment by jrottenberg** [comment]
Awesome thank you !

```
# test created for "https://pypi.org/pypi/reqman/json" !

- GET: /pypi/reqman/json
#- GET: https://pypi.org/pypi/reqman/json
  tests:
    - status: 200
    - json.info.author: <<myvar>>
```

-->

```
# reqman . myvar:manatlan
Use 'reqman.conf'
TEST: /mnt/0010_test.rml
* GET https://pypi.org/pypi/reqman/json --> 200
  - OK : status = 200
  - OK : json.info.author = "manatlan"

RESULT: 2/2 (1req(s))
```
